project:
  type: website

website:
  title: "PSY504 Lab Assignments"
  description: "A blog of my stats assignments."
  navbar:
    right:
      - icon: fa-brands fa-github
        text: GitHub
        href: "https://github.com/bellafascendini"

blog:
  post-dir: posts 

