---
title: "PSY504 Assignments Blog"
format: html
---

Lab 2 [Logistic Regression Assignment](assignments/logistic_regression.html)

Lab 3 [Ordinal Regression Assignment](assignments/ordinal_regression.html)

Lab 4 [Multinomial Regression Assignment](assignments/multinomial_regression.html)

Lab 5 [Poisson Regression Assignment](assignments/poisson_regression.html)

Lab 6 [Multilevel Modeling Walkthrough Assignment](assignments/multilevel-modeling-walkthrough/multilevel_modeling_walkthrough.html)

Lab 7 [Multilevel Modeling2 Assignment](assignments/multilevel_modeling2.html)

Lab 8 [Bayesian Modeling Assignment](assignments/bayesian_modeling.html)

Lab 9 [Bayesian Modeling2 Assignment](assignments/bayesian_modeling_part2.html)

Lab 10a [Bayesian Modeling Priors Predictive Checks Assignment](assignments/bayes_priors_predictive_checks.html)

Lab 10b [Bayesian Modeling HMC Diagnostics Assignment](assignments/bayes_HMC_diagnostics.html)

Lab 11 [Missing Data Assignment](assignments/missing_data.html)


